# Generated by Django 3.2.9 on 2021-11-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0002_telegramusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='creation_date',
            field=models.DateTimeField(default=None, verbose_name='creation_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='last_login_date',
            field=models.DateTimeField(default=None, verbose_name='creation_date'),
            preserve_default=False,
        ),
    ]
