# Generated by Django 3.2.9 on 2021-11-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0003_auto_20211130_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUsers',
            new_name='TelegramUser',
        ),
    ]
