# Generated by Django 3.2.9 on 2021-11-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0005_auto_20211130_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_telegra_id',
            new_name='user_telega_id',
        ),
    ]
