# Generated by Django 3.2.9 on 2021-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0006_rename_user_telegra_id_telegramuser_user_telega_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bad_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='ban'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='temp_block',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='temp_block_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_telega_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
