# Generated by Django 3.2.9 on 2021-12-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0010_citydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='bad_date',
            new_name='ban_date',
        ),
    ]
